#!/bin/bash


# выставляем значение балансов для предварительной тренировки декодера
#python3 setup_balance.py 0.2
#python3 setup_balance.py 0.75
#python3 setup_balance.py 0.9

# немного тренируем ТОЛЬКО ДЕКОДЕР
# при размере батча 256
#   скорость обучения 1e-3 подходит для двухслойного декодера
#   скорость 1e-4 подходит для 4-слойного декодера
# при размере батча 1024
#   скорость 2e-4 подходит для 4-слойного декодера
#python3 balance_training_3.py new 400 --lr 2e-4
#python3 balance_training_3.py new 900 --lr 2e-4

# выставляем стартовое значение балансов для их обучения
#python3 setup_balance.py 0.7

# тренируем балансы и декодер
#python3 balance_training_3.py continue 300 --lr 1e-4
#python3 balance_training_3.py continue 1800 --lr 3e-4
#python3 balance_training_3.py continue 7200 --lr 3e-4
#python3 balance_training_3.py continue 10800 --lr 3e-4
#python3 balance_training_3.py continue 14400 --lr 3e-4
#python3 balance_training_3.py continue 21600 --lr 3e-4


#python3 balance_training_3.py continue 2000 --lr 3e-4





mb=1024

#python3 setup_balance.py 0.75 0.7 0.7 0.3 -- с этим набором что-то не так

#python3 setup_balance.py 0.75 0.75 0.75 0.75
#python3 setup_balance.py 0.75 0.75 0.75 0.3
#python3 setup_balance.py 0.75 0.7 0.75 0.75
#python3 setup_balance.py 0.75 0.75 0.7 0.75

#python3 setup_balance.py 0.75 0.75 0.5 0.75
#python3 setup_balance.py 0.9 0.9 0.9 0.5

#python3 setup_balance.py 0.75 0.65 0.5 0.5 # получается, результат наиболее чувствителен к assoc
python3 setup_balance.py 0.75 0.75 0.7 0.5

# первое приближение (для самых частотных)
#python3 balance_training_3.py new 600 --rnd_dataset --lr 2e-4 --batch 1280
#python3 balance_training_3.py continue 600 --train_cat_balances --train_ass_balances --train_gra_balances --rnd_dataset --lr 2e-4 --batch $mb
#python3 balance_training_3.py continue 600 --train_cat_balances --rnd_dataset --lr 2e-4 --batch $mb
#python3 see_balance.py

for i in {1..3}; do
##  #python3 balance_training_3.py new 600 --hide_sfx --rnd_dataset --lr 2e-4 --batch 1280
##  #python3 balance_training_3.py continue 1800 --train_stem_balances --hide_sfx --rnd_dataset --lr 2e-4 --batch 1280
  python3 balance_training_3.py new 600 --rnd_dataset --lr 2e-4 --batch $mb
  python3 balance_training_3.py continue 1800 --train_cat_balances --train_ass_balances --rnd_dataset --lr 2e-4 --batch $mb
  python3 see_balance.py
done

#for i in {1..2}; do
#  python3 balance_training_3.py new 600 --rnd_dataset --lr 2e-4 --batch $mb
#  python3 balance_training_3.py continue 1800 --train_sfx_balances --rnd_dataset --lr 2e-4 --batch $mb
#  python3 see_balance.py
#done

#python3 balance_training_3.py new 600 --rnd_dataset --lr 2e-4 --batch $mb
#python3 see_balance.py
#python3 balance_training_3.py continue 10800 --train_stem_balances --train_sfx_balances --rnd_dataset --lr 2e-4 --batch $mb
#python3 see_balance.py

